<a href="https://colab.research.google.com/github/Leima20/Sprint_8_Leidy_Pimentel/blob/main/Sprint_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NIVEL 1

Exercici 1: Exploració inicial del dataset
🎯 Objectiu: entendre l’estructura general del dataset i detectar possibles problemes abans de començar a netejar o transformar dades.
En aquest exercici has de realitzar una exploració inicial del DataFrame per respondre, com a mínim, a les següents preguntes:

» Quantes files i columnes té el dataset?
» Quin tipus de dades conté cada columna?
» Hi ha files duplicades?
» Les dades semblen coherents a primera vista?
» Detectes possibles problemes o inconsistències evidents?
Per fer-ho, hauràs de:

» Analitzar les dimensions del dataset
» Mostrar una mostra representativa de files
» Revisar els tipus de variables
» Les dades semblen coherents a primera vista?
» Detectar files duplicades
» Identificar i descriure possibles problemes inicials (sense solucionar-los encara)

Introducción

En este ejercicio realizamos la carga y exploración básica del dataset de empleados para verificar su integridad, estructura y calidad antes de proceder a la limpieza.

Importaciones

In [ ]:
import pandas as pd

Importamos el dataframe

In [10]:
file_path = 'sprint8_complex.xlsx'
df = pd.read_excel(file_path)

df

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,1002,Alba,MuÃ±oz,97954019T,Espanya,Bilbao,25.0,10.0,1983.0,D,"1,409 â‚¬",NaN,True,Grup B,Responsable de vendes,0.0,NaN,NaN,NaN,14.7
1006,1003,Claudia,Gil Ferrer,55297384F,Espanya,ValÃ¨ncia,1.0,11.0,1981.0,H,1.789 â‚¬,NaN,True,Grup B,Responsable de vendes,0.0,True,29952.0,9.2,20.3
1007,1004,Oriol,Ferrer,52590001R,Espanya,Zaragoza,15.0,7.0,1973.0,D,786â‚¬,NaN,True,Grup A,Analista,0.0,True,81381.0,6.5,13.9
1008,1005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1009,1006,???,###,XXXX,Narnia,Desconeguda,-99.0,99.0,3000.0,??,molts,NaN,NaN,Z,???,NaN,NaN,NaN,NaN,NaN

**Filas y columnas del dataset**

Se emplea 'df.shape' para conocer las dimensiones del dataset. l dataset está compuesto por **1010 filas y 20 columnas.** Esta información proporciona una visión general del volumen de datos disponible y sirve como punto de partida para el análisis exploratorio.

In [11]:

filas, columnas = df.shape
print(f" El dataset tiene {filas} filas y {columnas} columnas ")

 El dataset tiene 1010 filas y 20 columnas

**Tipos de datos que contiene cada columna**

Todas las columnas del dataset se han cargado con el tipo de dato object. Esto indica que Pandas ha interpretado todas las variables como texto, por lo que será necesario revisar si existen columnas que deberían convertirse a otros tipos de datos, como valores numéricos o fechas, para facilitar su análisis.

In [12]:
print("\n--- Tipos de datos ---")
print(df.info())

--- Tipos de datos ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 20 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Dades de l'enquesta de treballadors 2025  1008 non-null   object
 1   Unnamed: 1                                1007 non-null   object
 2   Unnamed: 2                                1007 non-null   object
 3   Unnamed: 3                                1007 non-null   object
 4   Unnamed: 4                                1007 non-null   object
 5   Unnamed: 5                                1007 non-null   object
 6   Unnamed: 6                                1007 non-null   object
 7   Unnamed: 7                                1007 non-null   object
 8   Unnamed: 8                                1007 non-null   object
 9   Unnamed: 9                                967 non-null    object
 10  Unnamed: 10                               1007 non-null   object
 11  Unnamed: 11                               420 non-null    object
 12  Unnamed: 12                               586 non-null    object
 13  Unnamed: 13                               1006 non-null   object
 14  Unnamed: 14                               1006 non-null   object
 15  Unnamed: 15                               710 non-null    object
 16  Unnamed: 16                               659 non-null    object
 17  Unnamed: 17                               316 non-null    object
 18  Unnamed: 18                               262 non-null    object
 19  Unnamed: 19                               937 non-null    object
dtypes: object(20)
memory usage: 157.9+ KB
None

**Duplicados**

Se utiliza el método duplicated().sum() para identificar el número de filas completamente duplicadas en el dataset.

Los resultados muestran que el dataset no contiene filas completamente duplicadas, ya que se han detectado 0 registros duplicados.

In [13]:
duplicados = df.duplicated().sum()
print(f"el Dataset contiene {duplicados} filas duplicadas")

el Dataset contiene 0 filas duplicadas

**Coherencia de los datos**

La muestra aleatoria permite comprobar que el dataset corresponde a un conjunto de datos de empleados y que, en general, mantiene una estructura consistente. Sin embargo, durante la inspección visual se observan algunos indicios de posibles inconsistencias que deberán analizarse con mayor detalle en los siguientes apartados.

Al revisar las primeras filas del dataset `display(df.head())` a primera vista, el contenido parece corresponder a información de empleados. Sin embargo, se observa que las tres primeras filas no contienen datos del dataset, sino información adicional del archivo (como un título y filas vacías). Asimismo, los nombres de las variables no se han interpretado correctamente, apareciendo columnas con nombres como **Unnamed**. Esto indica que el archivo no se ha leído con la fila de encabezados adecuada, aspecto que será necesario corregir mas adelante.

In [18]:
display(df.head())

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,CÃ rrec,Nombre_fills,Te_cotxe,Km_anuals,Consum_mitja_L_100km,Temperatura_mitjana_ciutat
3,0,Joana,Gil Navarro,66722344X,Espanya,Valladolid,23.0,3.0,1958.0,Dona,"1,469 â‚¬",True,NaN,Grup B,Cap de projecte,3.0,True,32108.0,25.0,10.1
4,1,Marc,MuÃ±oz,48840994W,Espanya,Alacant,8.0,11.0,1960.0,H,"2,718 â‚¬",NaN,True,Grup C,Senior analyst,0.0,True,19496.0,10.4,18.7

**Posibles problemas o inconsistencias evidentes**

Se han encontrado algunas inconsistencias al revisar el dataset:

 * Los nombres de los encabezados de las columnas no se han interpretado correctamente debido a la estructura del archivo.
 * Se observan inconsistencias en el formato de la columna de salarios, por lo que será necesario revisar su conversión a un tipo numérico.
 * La variable Género presenta una falta de estandarización, ya que contiene valores como Dona, Home, D, H, F, M, NC, A, ?? y valores nulos.
 * Se detectan problemas de codificación (encoding), reflejados en caracteres mal representados, como CÃrrec.
 * Existe una posible redundancia estructural entre las variables Fills, No Fills y Nombre_fills, por lo que será necesario comprobar si contienen información duplicada o inconsistente.

Exercici 2:

 Validacions bàsiques de les dades i decisions d'eliminació
🎯 Objectiu: assegurar que les dades compleixen unes condicions mínimes de qualitat i determinar quines files poden continuar sent analitzades i quines s'han de descartar.
En aquest exercici hauràs de validar aspectes clau del dataset que són crítics en qualsevol context real d'anàlisi de dades, prenent decisions justificades sobre la validesa o eliminació de registres.

Aspectes a validar:

» Existeixen identificadors únics (DNI) per a cada persona?
» Què faràs amb les files duplicades o registres repetits?
» Hi ha valors obligatoris que falten o informació incoherent?
» Detectes formats incorrectes, errors de codificació o valors impossibles?
Concretament, hauràs de:

» Corregir possibles problemes de codificació i accentuació en els noms de les columnes i en els valors de text, si escau.
» Detectar i eliminar files duplicades exactes, indicant quants registres s'han eliminat.
» Comprovar la unicitat del DNI. En cas de detectar DNIs duplicats, hauràs d'analitzar la coherència de la informació associada i descartar o anul·lar els registres que no siguin fiables, justificant clarament la decisió presa.
» Identificar els camps clau que no haurien de contenir valors nuls, detectar registres amb informació insuficient i eliminar únicament aquelles files completament buides o amb informació irrecuperable o no substituïble, explicant per què no és possible ni raonable imputar-les.

Importamos las librerias necesarias

In [1]:
import pandas as pd
import re
from collections import defaultdict

Definimos una función auxiliar para reparar los errores de codificación.

In [ ]:
def reparar_codificacion(texto) -> str:
    try:
        return texto.encode("cp1252").decode("utf-8")
    except (UnicodeEncodeError, UnicodeDecodeError):
        return texto

Leemos el fichero excel y lo cargamos en un DataFrame de pandas. Ignoramos las 2 primeras filas y usamos la tercera fila como cabecera.
Además, establecemos la primera columna como índice del DataFrame.
Después hacemos una copia del DataFrame original para trabajar sobre ella y no modificar el original.

In [ ]:
df = pd.read_excel("sprint8_complex.xlsx", header=3, index_col=0)
nuevo_df = df.copy()

Comprobamos y reparamos la codificación del texto de las cabeceras de las columnas.

In [ ]:
cabeceras_originales = nuevo_df.columns
print(f"Cabeceras originales: {cabeceras_originales.tolist()}")
cabeceras_reparadas = cabeceras_originales.map(
    lambda x: reparar_codificacion(x) if isinstance(x, str) else x
)

cabeceras_modificadas = cabeceras_originales[cabeceras_originales != cabeceras_reparadas]

if len(cabeceras_modificadas) > 0:
    print(
        f"Se han reparado las cabeceras de las columnas "
        f"{cabeceras_modificadas.tolist()} debido a problemas de codificación."
    )
    nuevo_df.columns = cabeceras_reparadas

Reparamos el contenido de las columnas de texto.

In [ ]:
for columna in nuevo_df.select_dtypes(include=["object", "string"]):
    serie_original = nuevo_df[columna]

    serie_reparada = serie_original.map(
        lambda x: reparar_codificacion(x) if isinstance(x, str) else x
    )

    reparados = (serie_original != serie_reparada).sum()

    if reparados > 0:
        print(
            f"Se han reparado {reparados} valores en la columna "
            f"'{columna}' debido a problemas de codificación."
        )
        nuevo_df[columna] = serie_reparada

Obtenemos las filas duplicadas exactas y las eliminamos.

In [ ]:
filas_duplicadas = nuevo_df[nuevo_df.duplicated(keep="first")]

if not filas_duplicadas.empty:
    print("Detectadas filas duplicadas exactas:")
    print(filas_duplicadas)
else:
    print("No se han encontrado filas duplicadas exactas.")

filas_iniciales = len(nuevo_df)
nuevo_df.drop_duplicates(inplace=True)

print(f"\nSe han eliminado {filas_iniciales - len(nuevo_df)} filas duplicadas exactas.")

Buscamos todos aquellos DNIs que aparecen más de una vez y eliminamos todas las filas en las que aparecen, ya que no es posible determinar cual de las filas (o ninguna) tiene los datos correctos.

In [ ]:
duplicados = nuevo_df[nuevo_df.duplicated(subset=["DNI"], keep=False)]

if duplicados.empty:
    print("No se han encontrado DNIs duplicados.")
else:
    for dni, grupo in duplicados.groupby("DNI"):
        print(f"\nFilas con el DNI duplicado {dni}:")
        print(grupo)

        nuevo_df.drop(index=grupo.index, inplace=True)
        print(f"Se han eliminado {len(grupo)} filas con el DNI {dni}.")

Buscamos y eliminamos todas las filas que no tienen la informacion minima necesaria (Nombre, Apellidos y DNI) rellenada y sin simbolos.

In [ ]:
mask_na = (
    df["Nom"].isna()
    & df["Cognoms"].isna()
    & df["DNI"].isna()
)

if mask_na.any():
    print("Las siguientes filas contienen valores NA en los campos Nom, Cognoms y DNI y se eliminarán:\n")
    print(df.loc[mask_na])

df = df.loc[~mask_na].copy()

print(f"\nSe han eliminado {mask_na.sum()} filas.\n")

mask_simbolos = (
    df["Nom"].fillna("").str.fullmatch(r"[^A-Za-zÀ-ÿ0-9]+")
    | df["Cognoms"].fillna("").str.fullmatch(r"[^A-Za-zÀ-ÿ0-9]+")
    | df["DNI"].fillna("").str.fullmatch(r"[^A-Za-zÀ-ÿ0-9]+")
)

if mask_simbolos.any():
    print("Las siguientes filas contienen símbolos no válidos en alguno de los campos Nom, Cognoms o DNI y se eliminarán:\n")
    print(df.loc[mask_simbolos])

df = df.loc[~mask_simbolos].copy()

print(f"\nSe han eliminado {mask_simbolos.sum()} filas.\n")

In [ ]:
Comprobamos el contenido de las columas para detectar y corregir valores imposibles.
Para ello, definimos los rangos de valores permitidos para cada columna y los tipos de datos esperados.

In [ ]:
ENTEROS = {
    "Dia de Naixement": (1, 31),
    "Mes de Naixement": (1, 12),
    "Any de Naixement": (1900, 2026),
    "Salari mensual": (0, None),
    "Nombre_fills": (0, None),
    "Km_anuals": (0, None),
}

FLOATS = {
    "Consum_mitja_L_100km": (0, None),
    "Temperatura_mitjana_ciutat": (-273.15, None),
}

STRINGS = {
    "Gènere": {"H", "D"},
    "Grup Professional": {
        "Grup A",
        "Grup B",
        "Grup C",
        "Grup D",
    },
}

BOOLEANOS = [
    "Te_cotxe",
    "Fills",
    "No Fills",
]

Creamos un diccionario para almacenar los errores encontrados en cada fila del DataFrame.
Validamos los valores de las columnas según los rangos y tipos definidos. Empezamos por los enteros.

In [ ]:
errores = defaultdict(list)

for columna, (minimo, maximo) in ENTEROS.items():

    valores = pd.to_numeric(df[columna], errors="coerce")

    # No es un número entero
    mask = valores.isna()

    for indice in df.index[mask]:
        errores[indice].append(
            f"{columna}: '{df.at[indice, columna]}' no es un número entero."
        )

    # Menor que el mínimo
    if minimo is not None:

        mask = valores.notna() & (valores < minimo)

        for indice in df.index[mask]:
            errores[indice].append(
                f"{columna}: '{df.at[indice, columna]}' es menor que {minimo}."
            )

    # Mayor que el máximo
    if maximo is not None:

        mask = valores.notna() & (valores > maximo)

        for indice in df.index[mask]:
            errores[indice].append(
                f"{columna}: '{df.at[indice, columna]}' es mayor que {maximo}."
            )

Hacemos lo mismo para los floats.

In [ ]:
# Floats.
for columna, (minimo, maximo) in FLOATS.items():

    valores = pd.to_numeric(df[columna], errors="coerce")

    mask = valores.isna()

    for indice in df.index[mask]:
        errores[indice].append(
            f"{columna}: '{df.at[indice, columna]}' no es un número decimal."
        )

    if minimo is not None:

        mask = valores.notna() & (valores < minimo)

        for indice in df.index[mask]:
            errores[indice].append(
                f"{columna}: '{df.at[indice, columna]}' es menor que {minimo}."
            )

    if maximo is not None:

        mask = valores.notna() & (valores > maximo)

        for indice in df.index[mask]:
            errores[indice].append(
                f"{columna}: '{df.at[indice, columna]}' es mayor que {maximo}."
            )

Hacemos lo mismo para los strings.

In [ ]:
# Strings.
for columna, permitidos in STRINGS.items():

    # No es una cadena
    mask = ~df[columna].map(lambda x: isinstance(x, str))

    for indice in df.index[mask]:
        errores[indice].append(
            f"{columna}: '{df.at[indice, columna]}' no es una cadena de texto."
        )

    # Valor no permitido
    mask = (
        df[columna].map(lambda x: isinstance(x, str))
        & ~df[columna].isin(permitidos)
    )

    for indice in df.index[mask]:
        errores[indice].append(
            f"{columna}: '{df.at[indice, columna]}' "
            f"no pertenece a {sorted(permitidos)}."
        )

Hacemos lo mismo para los booleanos.

In [ ]:
#Booleanos.
for columna in BOOLEANOS:
    mask = ~df[columna].map(lambda x: isinstance(x, bool))
    for indice in df.index[mask]:
        errores[indice].append(
            f"{columna}: '{df.at[indice, columna]}' no es un valor booleano."
        )

Hacemos lo mismo para los DNIs. Comprobamos que tengan 8 numeros y una letra.

In [ ]:
#DNI.
dni = (
    df["DNI"]
    .astype("string")
    .str.strip()
    .str.upper()
)

mask = ~dni.str.fullmatch(r"\d{8}[A-Z]", na=False)

for indice in df.index[mask]:
    errores[indice].append(
        f"DNI: '{df.at[indice, 'DNI']}' no tiene el formato correcto."
    )

Comprobamos que las columnas Fills y No Fills no sean iguales, pues sería una contradicción.

In [ ]:
#Fills y no fills.
mask = (
    df["Fills"].notna()
    & df["No Fills"].notna()
    & (df["Fills"] == df["No Fills"])
)

for indice in df.index[mask]:

    errores[indice].append(
        f"Fills={df.at[indice,'Fills']} y "
        f"No Fills={df.at[indice,'No Fills']} "
        "deberían ser valores opuestos."
    )

Mostramos los errores encontrados en cada fila del DataFrame.

In [ ]:
for fila, lista in errores.items():

    print(f"\nFila {fila}")

    for error in lista:
        print(f"  • {error}")